site_name: STAR WARS
site_description: Repositório do Grupo 02 da disciplina Sistema de Banco de Dados 1.
repo_url: https://github.com/SBD1/Grupo02-starWars

nav:
  - Página Inicial: index.md
  - Apresentação Jogo:
    - Glosario Geral: glossario.md 
    - Episódio I:
        - Sobre o Jogo: detalhes_ep_1.md
  - Módulo 1:
    - Modelo Entidade-Relacionamento: modulo1/mer.md
    - Diagrama Entidade-Relacionamento: modulo1/der.md
    - Atas: 
      - 30/01/2022: modulo1/atas/30-01-2022.md
  - Módulo 2: 
    - Domínios: modulo2/dominio.md
    - Modelo Relacional: modulo2/modelo-relacional.md
  - Módulo 3: 
    - Normalização: modulo3/normalizacao.md
  - Módulo 4:
    - Scripts: modulo4/resultadosMD4.md
    - Novas versões:
      - Diagrama Entidade-Relacionamento: modulo1/der.md
      - Modelo relacional: modulo4/modelo-relacional/modelo-relacional-atualizado.md
      - Dados jogo:  modulo4/populacao-banco/dados.md
  - Módulo 5:
    - Álgebra Relacional: modulo5/algebra-relacional.md

extra_css:
  - stylesheets/extra.css

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette: 
    - scheme: sw
  language: pt
  logo: assets/icon.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SBD1/Grupo02-starWars

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
        
